import nodemailer from 'nodemailer';
import { config } from '../config';

let transporter: nodemailer.Transporter | null = null;

function getTransporter(): nodemailer.Transporter {
  if (!transporter) {
    const smtpConfig = (config as any).smtp;
    if (!smtpConfig?.host) {
      throw new Error('SMTP not configured. Set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD environment variables.');
    }
    transporter = nodemailer.createTransport({
      host: smtpConfig.host,
      port: smtpConfig.port,
      secure: smtpConfig.port === 465,
      auth: smtpConfig.user ? {
        user: smtpConfig.user,
        pass: smtpConfig.password,
      } : undefined,
    });
  }
  return transporter;
}

interface EmailAttachment {
  filename: string;
  content: Buffer | string;
  contentType?: string;
}

interface SendReportEmailOptions {
  to: string;
  subject: string;
  body: string;
  attachments?: EmailAttachment[];
}

export async function sendReportEmail(options: SendReportEmailOptions): Promise<void> {
  const transport = getTransporter();
  const smtpConfig = (config as any).smtp;

  await transport.sendMail({
    from: smtpConfig.from || `CIVICycle <${smtpConfig.user}>`,
    to: options.to,
    subject: options.subject,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background-color: #10b981; padding: 20px; text-align: center;">
          <h1 style="color: white; margin: 0;">CIVICycle</h1>
        </div>
        <div style="padding: 20px; background-color: #f9fafb;">
          ${options.body}
        </div>
        <div style="padding: 10px 20px; background-color: #e5e7eb; text-align: center; font-size: 12px; color: #6b7280;">
          Generated by CIVICycle on ${new Date().toLocaleString()}
        </div>
      </div>
    `,
    attachments: options.attachments?.map((a) => ({
      filename: a.filename,
      content: a.content,
      contentType: a.contentType,
    })),
  });
}

export function isEmailConfigured(): boolean {
  const smtpConfig = (config as any).smtp;
  return !!(smtpConfig?.host);
}
