import nodemailer from 'nodemailer';
import { config } from '../config';
import { query } from '../db';

let transporter: nodemailer.Transporter | null = null;
let cachedSmtpConfig: any = null;

async function getSmtpConfig(): Promise<any> {
  if (cachedSmtpConfig) return cachedSmtpConfig;

  // Try loading from database first
  try {
    const result = await query(
      "SELECT key, value FROM app_settings WHERE category = 'smtp'"
    );
    if (result.rows.length > 0) {
      const dbSettings: Record<string, string> = {};
      for (const row of result.rows) {
        dbSettings[row.key] = row.value;
      }
      if (dbSettings.host) {
        cachedSmtpConfig = {
          host: dbSettings.host,
          port: parseInt(dbSettings.port || '587', 10),
          user: dbSettings.user || '',
          password: dbSettings.password || '',
          from: dbSettings.from || '',
        };
        return cachedSmtpConfig;
      }
    }
  } catch {
    // Table may not exist yet, fall through to env vars
  }

  // Fall back to env vars
  const envConfig = (config as any).smtp;
  if (envConfig?.host) {
    cachedSmtpConfig = envConfig;
  }
  return cachedSmtpConfig;
}

// Clear cached config so changes take effect
export function clearSmtpCache(): void {
  transporter = null;
  cachedSmtpConfig = null;
}

async function getTransporter(): Promise<nodemailer.Transporter> {
  const smtpConfig = await getSmtpConfig();
  if (!smtpConfig?.host) {
    throw new Error('SMTP not configured. Configure email settings in Admin Panel or set SMTP environment variables.');
  }

  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: smtpConfig.host,
      port: smtpConfig.port,
      secure: smtpConfig.port === 465,
      auth: smtpConfig.user ? {
        user: smtpConfig.user,
        pass: smtpConfig.password,
      } : undefined,
    });
  }
  return transporter;
}

interface EmailAttachment {
  filename: string;
  content: Buffer | string;
  contentType?: string;
}

interface SendReportEmailOptions {
  to: string;
  subject: string;
  body: string;
  attachments?: EmailAttachment[];
}

export async function sendReportEmail(options: SendReportEmailOptions): Promise<void> {
  const transport = await getTransporter();
  const smtpConfig = await getSmtpConfig();

  await transport.sendMail({
    from: smtpConfig.from || `CIVICycle <${smtpConfig.user}>`,
    to: options.to,
    subject: options.subject,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background-color: #10b981; padding: 20px; text-align: center;">
          <h1 style="color: white; margin: 0;">CIVICycle</h1>
        </div>
        <div style="padding: 20px; background-color: #f9fafb;">
          ${options.body}
        </div>
        <div style="padding: 10px 20px; background-color: #e5e7eb; text-align: center; font-size: 12px; color: #6b7280;">
          Generated by CIVICycle on ${new Date().toLocaleString()}
        </div>
      </div>
    `,
    attachments: options.attachments?.map((a) => ({
      filename: a.filename,
      content: a.content,
      contentType: a.contentType,
    })),
  });
}

export async function isEmailConfigured(): Promise<boolean> {
  const smtpConfig = await getSmtpConfig();
  return !!(smtpConfig?.host);
}
